import { PrMetadata, FileChange } from '../types';
export interface HunkContext { hunkHeader: string; changedLines: string; surroundingBefore: string[]; surroundingAfter: string[]; }
export function extractChangedFiles(pr: PrMetadata): FileChange[] { return pr.files.filter(f => f.patch); }
export function extractHunks(patch: string): HunkContext[] { const lines = patch.split('\n'); const hunks: HunkContext[] = []; let cur: string[] = []; let inH = false; for (let i = 0; i < lines.length; i++) { const l = lines[i]; if (l.startsWith('@@')) { if (cur.length > 0) hunks.push(buildHC(cur)); cur = [l]; inH = true; } else if (inH) cur.push(l); } if (cur.length > 0) hunks.push(buildHC(cur)); return hunks; }
function buildHC(lines: string[]): HunkContext { const hdr = lines[0]; const cl: string[] = []; const sb: string[] = []; const sa: string[] = []; for (let i = 1; i < lines.length; i++) { const l = lines[i]; if (l.startsWith('+') || l.startsWith('-')) cl.push(l); else if (l.startsWith(' ') || !l.startsWith('\\')) { if (cl.length === 0) sb.push(l); else sa.push(l); } } return { hunkHeader: hdr, changedLines: cl.join('\n'), surroundingBefore: sb, surroundingAfter: sa }; }
export function extractFileStructure(fileContent: string): string { if (!fileContent) return ''; const lines = fileContent.split('\n'); const s: string[] = []; for (const l of lines) { const t = l.trim(); const fm = t.match(/(?:export\s+)?(?:async\s+)?function\s+(\w+)/); if (fm) { const pm = t.match(/\(([^)]*)\)/); s.push(`function ${fm[1]}(${pm?.[1]?.substring(0,60)||''})`); continue; } const am = t.match(/(?:export\s+)?const\s+(\w+)\s*=\s*(?:async\s*)?\(/); if (am) { s.push(`const ${am[1]} = (...)`); continue; } const cm = t.match(/class\s+(\w+)/); if (cm) { s.push(`class ${cm[1]}`); continue; } const im = t.match(/import\s+.*\s+from\s+['"](.+)['"]/); if (im) { s.push(`import "${im[1]}"`); } } return s.join('\n'); }
// NOTE: GitHub REST API (pulls.listFiles) returns patches with default ~3 lines of context.
// Actual surrounding context available depends on API response.
const CONTEXT_WINDOW = 80;
export function buildLLMPrompt(file: { filename: string; patch?: string; additions: number; deletions: number }, pr: PrMetadata, fileContent: string): string { const hunks = extractHunks(file.patch || ''); const structure = extractFileStructure(fileContent); const cs = hunks.map((h, i) => { const b = h.surroundingBefore.slice(-CONTEXT_WINDOW).join('\n'); const a = h.surroundingAfter.slice(0, CONTEXT_WINDOW).join('\n'); return `### Hunk ${i+1}\n${h.hunkHeader}\n\`\`\`\n${b}\n${h.changedLines}\n${a}\n\`\`\``; }).join('\n\n'); return `You are a code review expert. Analyze code changes for: security issues, quality issues, style issues. PR: ${pr.title}. File: ${file.filename} (+${file.additions}/-${file.deletions}). Structure:\n${structure||'N/A'}\n\n${cs}\n\nFor each issue, output ONE JSON object per line (JSONL format — no array brackets, no commas between objects). Each line must be a complete, valid JSON object like: {"file":"${file.filename}","line":<N>,"category":"security|quality|style","severity":"critical|warning|info","title":"...","description":"...","suggestion":"...","codeSnippet":"...","confidence":<0-1>}. Only confidence >= 0.7. Do NOT wrap in an array. Do NOT add markdown fences.`; }
