import { Finding } from '../types'; import { v4 as uuid } from 'uuid';
export interface L1Rule { id: string; name: string; category: 'security'|'quality'|'style'; severity: 'critical'|'warning'|'info'; description: string; suggestion: string; check: (line: string, lineNum: number, filename: string, fullPatch: string) => Finding | null; }
const SAFE_GLOBALS=new Set(['Math','Object','Array','JSON','console','process','Date','String','Number','Boolean','RegExp','Map','Set','Promise','Error','Buffer','Symbol','Reflect','Intl','parseInt','parseFloat','isNaN','isFinite','undefined','null','this','arguments','module','exports','require','global','globalThis','window','document','navigator','localStorage','sessionStorage','crypto']);
const rules: L1Rule[] = [
  { id:'SEC-001',name:'Hardcoded Secret',category:'security',severity:'critical',description:'Potential hardcoded key/token/password.',suggestion:'Move to environment variables.',check(line,ln,fn){ const ps=[/(api[_-]?key|apikey|secret|password|token|auth)\s*[:=]\s*['"][A-Za-z0-9_\-\.]{12,}['"]/i, /['"]sk-[A-Za-z0-9]{20,}['"]/,/['"]ghp_[A-Za-z0-9]{20,}['"]/,/['"]AKIA[A-Z0-9]{16}['"]/,/['"]eyJ[A-Za-z0-9\-_=]+\.[A-Za-z0-9\-_=]+\.?[A-Za-z0-9\-_=]*['"]/]; for(const p of ps) if(p.test(line)) return mkF(fn,ln,'Hardcoded Secret',this,0.95,this.id); return null; }},
  { id:'SEC-002',name:'SQL Injection',category:'security',severity:'critical',description:'String interpolation in SQL.',suggestion:'Use parameterized queries.',check(line,ln,fn){ if(/\b(?:SELECT|INSERT|UPDATE|DELETE)\b.+(?:\+\s*|\$\{)/i.test(line)&&!line.includes('?')) return mkF(fn,ln,'Potential SQL Injection',this,0.85,this.id); return null; }},
  { id:'SEC-003',name:'XSS Risk',category:'security',severity:'critical',description:'innerHTML or dangerouslySetInnerHTML.',suggestion:'Use textContent or sanitize.',check(line,ln,fn){ if(/\b(?:innerHTML|outerHTML|document\.write\(|dangerouslySetInnerHTML)\b/.test(line)) return mkF(fn,ln,'Potential XSS',this,0.8,this.id); return null; }},
  { id:'SEC-004',name:'Path Traversal',category:'security',severity:'critical',description:'File path with user input.',suggestion:'Validate and sanitize paths.',check(line,ln,fn){ if(/(?:readFile|open|path\.join)\(.*(?:req\.|params\.|query\.|body\.)/i.test(line)&&!/sanitiz|validat|filter|basename/i.test(line)) return mkF(fn,ln,'Path Traversal',this,0.75,this.id); return null; }},
  { id:'SEC-005',name:'Weak Crypto',category:'security',severity:'warning',description:'Weak algorithm (MD5/SHA1/DES/RC4).',suggestion:'Use AES-GCM or SHA-256.',check(line,ln,fn){ if(/\b(?:md5|sha1|des|rc4)\b/i.test(line)&&/(?:hash|encrypt|cipher|digest|createHash)/i.test(line)) return mkF(fn,ln,'Weak Crypto',this,0.9,this.id); return null; }},
  { id:'SEC-006',name:'Sensitive Log',category:'security',severity:'warning',description:'Logging sensitive data.',suggestion:'Redact before logging.',check(line,ln,fn){ if(/\b(?:console|logger)\.(?:log|info|debug|warn|error)\s*\(.*(?:password|token|secret|credential)/i.test(line)) return mkF(fn,ln,'Sensitive Log',this,0.85,this.id); return null; }},
  { id:'QUAL-001',name:'Null Reference',category:'quality',severity:'warning',description:'Possible null dereference.',suggestion:'Add null check or optional chaining.',check(line,ln,fn){ if(/\b[a-zA-Z_]\w*\.[a-zA-Z_]\w*/.test(line)&&!/\?\.|if\s*\(/.test(line)){ const baseMatch=/(\w+)\.\w+/.exec(line); if(baseMatch){ const baseId=baseMatch[1]; if(SAFE_GLOBALS.has(baseId))return null; } return mkF(fn,ln,'Potential Null Reference',this,0.55,this.id); } return null; }},
  { id:'QUAL-002',name:'Empty Catch',category:'quality',severity:'warning',description:'Empty catch block.',suggestion:'At minimum, log the error.',check(line,ln,fn,fp){ if(/catch\s*\(/.test(line)){ const ls=fp.split('\n'); let ib=0,hc=false; for(let i=ls.indexOf(line);i<ls.length;i++){ if(ls[i].includes('{'))ib++; if(ls[i].includes('}')){ib--; if(ib<=0)break; } const t=ls[i].replace(/^[\s\+\-]+/,'').trim(); if(t&&!t.startsWith('//')&&!t.startsWith('/*')&&i!==ls.indexOf(line)){hc=true;break;} } if(!hc) return mkF(fn,ln,'Empty Catch',this,0.95,this.id); } return null; }},
  { id:'QUAL-003',name:'Resource Leak',category:'quality',severity:'warning',description:'Resource opened without visible cleanup.',suggestion:'Use try-finally or use .close().',check(line,ln,fn,fp){ if(/(?:fs|fsPromises)\.open\s*\(|createWriteStream\s*\(|createReadStream\s*\(|createConnection\s*\(/.test(line)){ const ls=fp.split('\n');const idx=ls.indexOf(line);const next5=ls.slice(idx+1,idx+6).join('\n'); if(!/\.close\(|\.disconnect\(|finally/.test(line)&&!/\.close\(|\.disconnect\(|finally/.test(next5)) return mkF(fn,ln,'Resource Leak',this,0.6,this.id); } return null; }},
  // In JS's single-threaded event loop, async mutations between await points are not true race conditions. Flag only as a very low-confidence hint. { id:'QUAL-004',name:'Race Condition',category:'quality',severity:'warning',description:'Async mutation of shared state.',suggestion:'Consider using mutex or atomic operations if state is shared across requests.',check(line,ln,fn){ if(/await\s/.test(line)&&/\+\+|--|\+=|-=/.test(line)&&!/\bfor\s+await\s*\(/.test(line)) return mkF(fn,ln,'Race Condition',this,0.15,this.id); return null; }},
  { id:'QUAL-005',name:'Unreachable Code',category:'quality',severity:'info',description:'Code after return/throw.',suggestion:'Remove or move before return.',check(line,ln,fn,fp){ const s=line.replace(/^[+\-\s]+/,''); if(/^\s*return\b|^\s*throw\b/.test(s)){ const ls=fp.split('\n');const idx=ls.indexOf(line); const nl=idx>=0&&idx<ls.length-1?ls[idx+1].replace(/^[+\-\s]+/,'').trim():''; if(nl&&!nl.startsWith('}')&&!nl.startsWith('//'))return mkF(fn,ln,'Unreachable Code',this,0.75,this.id); } return null; }},
  { id:'STYLE-001',name:'Magic Number',category:'style',severity:'info',description:'Numeric literal without context.',suggestion:'Extract to named constant.',check(line,ln,fn){ if(/(?<![a-zA-Z0-9_#"''\/\-\$])\b(?!0\b|1\b|-1\b|2\b|100\b)\d{3,}\b/.test(line)&&!/import|const|enum|#define|version/.test(line)) return mkF(fn,ln,'Magic Number',this,0.65,this.id); return null; }},
  { id:'STYLE-002',name:'No Error Handling',category:'style',severity:'info',description:'Async op without error handling.',suggestion:'Add try-catch or .catch().',check(line,ln,fn,fp){ if(/await\s+\w/.test(line)){const ls=fp.split('\n');const idx=ls.indexOf(line); const nb=ls.slice(Math.max(0,idx-5),Math.min(ls.length,idx+5)).join('\n'); if(!nb.includes('try {')&&!nb.includes('.catch(')&&!nb.includes('catch (')) return mkF(fn,ln,'No Error Handling',this,0.55,this.id); } return null; }},
  { id:'STYLE-003',name:'Console Statement',category:'style',severity:'info',description:'console.log left in code.',suggestion:'Remove or use proper logger.',check(line,ln,fn){ if(/console\.(?:log|debug|warn)\s*\(/.test(line)&&!/eslint-disable/.test(line)) return mkF(fn,ln,'Console Statement',this,0.7,this.id); return null; }},
];
function mkF(fn:string,ln:number,t:string,r:L1Rule,c:number,rid:string):Finding { return { id:uuid(),file:fn,line:ln,category:r.category,severity:r.severity,title:t,description:r.description,suggestion:r.suggestion,codeSnippet:'',confidence:c,source:'L1',ruleId:rid }; }
export function runL1Analysis(prData: { files: { filename: string; patch?: string }[], diff: string }): Finding[] { const f:Finding[]=[]; for(const file of prData.files) { if(!file.patch)continue; const lines=file.patch.split('\n'); for(let i=0;i<lines.length;i++){ const l=lines[i]; if(!l.startsWith('+')||l.startsWith('+++'))continue; const s=l.substring(1); let ln=1; for(let j=0;j<=i;j++){ if(!lines[j].startsWith('-')&&!lines[j].startsWith('---'))ln++; } for(const r of rules){ try { const ff=r.check(s,ln,file.filename,file.patch!); if(ff)f.push(ff); }catch{} } } } return f; }
